name: Test
on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  check-file-changes:
    runs-on: ubuntu-latest
    name: "ChangeTogether test"
    steps:
      - name: Print sha
        shell: bash
        run: echo ${{ github.sha }}
      - name: Run Action
        uses: getsentry/hackweek-changetogether@main
        with:
          repo: ${{ github.repository }}
          target_rev: ${{ github.sha }}
